SCRIPT_DIR=/home/blu/.local/libexec/i3blocks

#[music-playing]
#command=playerctl metadata | awk -F'xesam:title' '{print $2}' | tr -d '\n' | awk '{$1=$1;print}' | cut -c -38
#interval=1
# [nvme-temps]
# interval=3
# command=sensors -j | jq -r '(.["nvme-pci-0100"]["Adapter"] + ": " + (.["nvme-pci-0100"]["Composite"]["temp1_input"]|tostring) + "°C, " + .["nvme-pci-3000"]["Adapter"] + ": " + (.["nvme-pci-3000"]["Composite"]["temp1_input"]|tostring) + "°C") | gsub("PCI adapter"; "nvme0n1") | gsub("nvme0n1 Temperature"; "nvme1n1 Temperature")'

# [nvme-temp-nvme1n1]
# interval=3
# command=sensors -j | jq '"nvme1n1 \(.["nvme-pci-3000"]["Composite"]["temp1_input"])°C"'

#[mhz]
#interval=1
#command=xrandr --verbose | grep "*current" | tail -n 1 | cut -d ')' -f 2 | cut -d '+' -f 1

#[xmode]
#interval=1
#command=xrandr --verbose | grep "*current" | tail -n 1 | cut -d '(' -f 1

#[hostname]
#interval=60
#command=hostname
#markup=pango
#color=#0ABCEF


#[vpn-location-mullvad]
#command=mullvad status | grep -o 'in .*' | cut -d' ' -f3-
#interval=60
#color=#FFF000

[ipinfo]
command=cat /dev/shm/ip-info
interval=30
color=#E89AF2

[calendar]
command=$SCRIPT_DIR/calendar
interval=1
LABEL=  -
DATEFMT=+%Y-%m-%d %H:%M:%S
# SHORTFMT=+%H:%M:%S
color=#FF8A65

[music-playing]
command=playerctl metadata | awk -F'xesam:title' '{print $2}' | tr -d '\n' | awk '{$1=$1;print}' | grep -oP "[\x{00}-\x{7F}]*" | cut -c -38 
interval=1

[wattage]
interval=1
#command= bash /home/blu/git/fritzbox-smarthome
#command=/usr/bin/ruby "/home/blu/.config/i3blocks/scripts/fritzbox-smarthome/battery-info.rb"
command=echo $(cat /dev/shm/device_table_fritzbox.txt)
color=#FFF33
#command=./scripts/wattage-ups.sh
#command=sudo pwrstat -status | grep "Load" | awk '{print $2, $3, $4}'
# markup=pango
#color=#FFF000


#[wattage]
#interval=1
#command=bash ./scripts/wattage-table.sh
#command=sudo pwrstat -status | grep "Load" | awk '{print $2, $3, $4}'
#markup=pango
#color=#FFF33
#color=#FFF000
