SCRIPT_DIR=/home/blu/.local/libexec/i3blocks

[memory-usage]
interval=persist
command=$SCRIPT_DIR/custom/memory2
markup=pango
label=mem:
#color=#FFA500


[cpu-temperature]
interval=3
command=$SCRIPT_DIR/temperature
separator=false
label=cpu:

[pavucontrol]
full_text=
command=pavucontrol

# [nvme-temp-nvme0n1]
# interval=3
# command=sensors -j | jq -r '(.["nvme-pci-0100"]["Adapter"] + ": " + (.["nvme-pci-0100"]["Composite"]["temp1_input"]|tostring) + "°C, " + .["nvme-pci-3000"]["Adapter"] + ": " + (.["nvme-pci-3000"]["Composite"]["temp1_input"]|tostring) + "°C") | gsub("PCI adapter"; "nvme0n1") | gsub("nvme0n1 Temperature"; "nvme1n1 Temperature")'

#[disk-usage]
#instance=/
#interval=30
#command=$SCRIPT_DIR/disk_usage format="{used:.1f}G used of {total:.1f}G"
#color=#FF0000
#separator=false

[sway-focused-window-appid]
label=app_id 
command=~/.config/i3blocks/scripts/sway-get-app-id.sh
interval=1
color=#F979FF

#[i3-focused-title]
#command=$SCRIPT_DIR/custom/i3-focusedwindow -title
#interval=3

#[i3-focused-pos]
#command=$SCRIPT_DIR/custom/i3-focusedwindow -pos
#interval=3

[i3-focused-window]
command=$SCRIPT_DIR/custom/i3-focusedwindow -class
interval=1

#[i3-focused-window-dimensions]
#command=$SCRIPT_DIR/custom/i3-focusedwindow -dim
#interval=3

[ipinfo]
command=curl -s ipinfo.io | jq -e '.org == "null" // "Loc null"'
interval=20
color=#F979FF

[vpn-location-mullvad]
command=mullvad status | grep -o 'in .*' | cut -d' ' -f3-
interval=20
color=#FFF000

[calendar]
command=$SCRIPT_DIR/calendar
interval=1
LABEL=  -
DATEFMT=+%Y-%m-%d %H:%M:%S
# SHORTFMT=+%H:%M:%S
color=#FF8A65

[indoor temp]
command=bash ./scripts/bedroom-get-temperature.sh
interval=60
color=#00BFA5

[indoor humidity]
command=bash ./scripts/bedroom-get-humidity.sh
interval=60
color=#BA68C8

#[indoor temp kitchen]
#command=bash ./scripts/kitchen-get-temperature.sh
#interval=60
#color=#00BFA5

#[indoor humidity kitchen]
#command=bash ./scripts/kitchen-get-humidity.sh
#interval=60
#color=#BA68C8

#[weather]
#command=curl -Ss "https://wttr.in/wiesloch?format=1&rand=$(date +%s)"
#command=bash /home/blu/.config/rofi/get-weather.sh
#interval=60
#color=#FFA726

#[adi2-dac fs connected]
#command=lsusb | grep -q "ADI-2" && echo "<span size='15000' font='FontAwesome'>  => 󰟀  </span>" || echo "<span size='20000' font='FontAwesome'> =>   </span>"
#interval=5
#color=#FFD600
#markup=pango
