SCRIPT_DIR=/home/blu/.local/libexec/i3blocks
CUSTOM_DIR=/home/blu/.config/i3blocks/i3blocks/custom

[available_space_sys]
command=df -BGiB / | awk 'NR==2{print $3" / "$2" "}'
interval=30
color=#FFDF00

[playing_now]
command=printf "%s\n" "$(cat /dev/shm/libsnd_mpris_Ambient 2>/dev/null)" || true
interval=1
