#!/bin/bash
ln -s /home/blu/git/mainrig-ms-7d51/.config/easyeffects /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/GKeys /home/blu/.config/sway/
ln -s /home/blu/git/mainrig-ms-7d51/.config/i3 /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/i3blocks /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/mako /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/micro /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/mpv /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/notes /home/blu/
ln -s /home/blu/git/mainrig-ms-7d51/.config/picom /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/pipewire /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/scripts /home/blu/
ln -s /home/blu/git/mainrig-ms-7d51/.config/scripts /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/sway /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/swayimg /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/swayr /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/wallpaper /home/blu/.config/sway/
ln -s /home/blu/git/mainrig-ms-7d51/.config/wofi /home/blu/.config/
