#!/bin/bash
ln -s /home/blu/git/mainrig-ms-7d51/.config/{easyeffects,GKeys,i3,i3blocks,mako,micro,mpv,notes,picom,pipewire,scripts,sway,swayimg,swayr,wallpaper,wofi} /home/blu/.config/
ln -s /home/blu/git/mainrig-ms-7d51/.config/scripts /home/blu/
ln -s /home/blu/git/mainrig-ms-7d51/.config/wallpaper /home/blu/.config/sway/
