# i3 Configuration File - mediakeys
$bm $meta+XF86AudioMute exec broadlink_cli --device @/home/blu/broadlink/BEDROOM.device --send @/home/blu/broadlink/RME/ADI2-DAC-FS/RME-switch-headphone-speaker
$bm XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
$bm XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
$bm XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
$bm XF86AudioNext exec playerctl next
$bm XF86AudioPause exec playerctl pause
$bm XF86AudioPlay exec playerctl play
$bm XF86AudioPrev exec playerctl previous
$bm XF86AudioRaiseVolume exec wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+
$bm XF86AudioStop exec playerctl play-pause