# ~/.config/sway/config

# Start dunst
exec dunst

# Watch borgbackups
exec /home/blu/scripts/cronjobs/watch-borgbackup-log.sh

# Start Crossover
exec ~/cxoffice/bin/crossover

# Run startup script
exec ~/scripts/autostart/script-startup.sh

# Start Alacritty with Trackma
exec alacritty --class=alacritty-trackma-curses -e trackma-curses 

# Start VS Code
exec code

# Start fcitx5
exec fcitx5 -d

# Start lxqt-policykit-agent
exec lxqt-policykit-agent

# Start FSearch with GDK_SCALE
exec GDK_SCALE=2 fsearch

# Start KeepassXC
exec keepassxc

# Start Mullvad VPN
exec mullvad connect

# Start Thunderbird
exec thunderbird

# Run remove urgent marks script after 10 seconds
exec sleep 10 && /home/blu/.config/i3/remove-urgent-marks.sh

# Start Firefox mappings script
exec ~/.config/i3/set-firefox-mappings-handlr.sh

# Reload i3blocks after 30 seconds
exec sleep 30 && ~/.config/i3/i3blocksreload.sh
