# i3 Configuration File - general window rules
$fw [$c="[aA]lacritty"] focus
$fw [$c="[kK]ate"] $fe, $rs 1020 1060
$fw [$c="[xX]fce4-terminal"] focus
$fw [$c="explorer.exe"] $mts
$fw [$c="kalgebra"] $fe
$fw [$c="Pavucontrol"] $fe
$fw [$c="xfce-polkit"] focus
$fw [$c="Yad"] $fe
$fw [$t="^Cultris II$"] $fe 
$fw [instance="mpvleft"] $mto $L, move down, focus, $bp0
$fw [instance="mpvright"] $mto $R, move down, focus, $fs, $bp0


# pls rename mpvfloatbottom to top right on left screen
$fw [instance="mpvfloattopright"] $mtw 1, $fe, $map 890px 27px, $rs 192px 108px, focus, border none
$fw [class="th19.exe"] $fe, border none
$fw [class="^ColorPicker$"] floating enable
# $fw [instance="mpvcapturecard"] $mtw $ws01-R, $fe, resize set 591px 1051 px, move position 2408px 354px, sticky enable, focus, border none
#$fw [instance="mpvcapturecard"] $mtw 53, $fe, resize set 891px 1584px, move position 0px 26px, focus, border none
$fw [instance="mpvcapturecard"] $mtw 54
$fw [instance="mpvcapturecard-secondary"] $mto $RR
$fw [instance="playlist-th"] $mto $L, focus, $bp0
$fw [title="^/dev/video0$"] $mtw 53, fullscreen enable
$fw [title="^/dev/video1$"] $mtw 54, fullscreen enable

$fw [class="^GParted$"] floating enable
$fw [class="^adi2remote.exe$"] floating enable