# i3 Configuration File - Applications Autostart

#exec firefox -P japanese-duolingo --class japanese-duolingo
#exec mscore # musescore
#exec sh ~/.config/ws-wall-switch.sh
$ea --no-startup-id dunst # for inotify-send etc
exec ~/apps/slippi/./Slippi.AppImage
exec ~/cxoffice/bin/crossover
exec ~/jd2/JDownloader2

# exec ~/scripts/mounts/mount-sshfs-user.sh
exec ~/scripts/mounts/mount-webdav.sh
exec ~/scripts/autostart/pre-wait-for-sshfsmounts-and-exec.sh
exec alacritty --class=alacritty-trackma-curses -e trackma-curses 

exec bash ~/.config/i3/unfocused-window-mute.sh
exec code # vscode
exec dex --autostart --environment i3
exec fcitx5 -d

#exec GDK_SCALE=2 fsearch # for making fsearch font double as large
exec idea # IntelliJ IDEA 
exec keepassxc
exec mullvad connect
exec mullvad-browser -P mullvadbrowser-real-debrid --class="mullvadbrowser-real-debrid"
exec numlockx
exec obsidian
exec parallel-launcher
exec python3 ~/broadlink/broadlink_ui.py 
exec ssh -L 5000:127.0.0.1:5000 -N root@tail.ws -p 764
exec steam
exec syncthing
exec thunderbird
exec virt-manager
exec wire-desktop 

# exec ares # other multi-platform-emulator
# exec simple64-gui
# exec bash /home/blu/scripts/autostart/delayed-i3-restart.sh
# exec autorandr --load work

# disabled ... wanna be sway compatible.

#$ea picom --config ~/.config/picom/picom.conf