# i3 Configuration File - general window rules
$fw [$c="[kK]ate"] $fe, $rs 1020 1060
$fw [instance="mpvright"] move to output $R, move down, focus, $fs, $bp0
$fw [instance="mpvleft"] move to output $L, move down, focus, $bp0
$fw [instance="playlist-th"] move to output $L, focus, $bp0
$fw [$c="[xX]fce4-terminal"] focus
$fw [$c="[aA]lacritty"] focus
$fw [$c="xfce-polkit"] focus
$fw [$c="explorer.exe"] $mts
$fw [$c="Pavucontrol"] $fe
$fw [$c="Yad"] $fe
$fw [$t="^Cultris II$"] $fe