entries=(
"th.*[0-9]{2}.exe|th0.*[0-9]{2}e.exe"
"simple64-gui"
"steam_app_759440"
"steam_app_554600"
"steam_app_438270"
"noita.exe,steam_app_881100"
"firefox-cyberchef"
"firefox-default"
"firefox-equatex"
"firefox-icloud-piano-ppt"
"firefox-japanese-books"
"firefox-japanese-bunpro-jp"
"firefox-japanese-genki-elementary"
"firefox-japanese-hiragana-kanatrainer"
"firefox-japanese-monkeytype"
"firefox-japanese-wanikani"
"firefox-linkedin"
"firefox-musictheory.net-exercises"
"firefox-musictheory.net-lessons"
"firefox-n64-hacks"
"firefox-photopea"
"firefox-posteo"
"firefox-SAP-WTS"
"firefox-utest"
"firefox-wire"
# nwjs is katakana war
)
