#context.properties = {
#    default.clock.allowed-rates    = [ 48000 ]
#    core.daemon                    = true
#    core.name                      = pipewire-0
#    default.clock.max-quantum      = 512
#    default.clock.min-quantum      = 64
#    default.clock.quantum          = 64
#    default.clock.rate             = 48000
#    link.max-buffers               = 16
#}

# context.modules = [
#     {
#         name = libpipewire-module-parametric-equalizer
#         args = {
#             remote.name            = "pipewire-0"
#             equalizer.filepath     = "/home/blu/git/mainrig-MS-7D51/.config/pipewire/pipewire.conf.d/EQ/HD800S/HD 800 S EQ amirm"
#             equalizer.description  = "HD 800 S EQ amirm"
#             audio.channels         = 2
#             audio.position         = [ FL, FR ]
#             playback.props = {
#                 node.name              = "EQ-amirm"
#             }
#             capture.props = {
#                 node.name              = "EQ-amirm"
#             }
#         }
#     },
#     {
#         name = libpipewire-module-parametric-equalizer
#         args = {
#             remote.name            = "pipewire-0"
#             equalizer.filepath     = "/home/blu/git/mainrig-MS-7D51/.config/pipewire/pipewire.conf.d/EQ/HD800S/HD 800 S EQ crinacle GRAS 43AG-7"
#             equalizer.description  = "HD 800 S EQ crinacle GRAS 43AG-7"
#             audio.channels         = 2
#             audio.position         = [ FL, FR ]
#             playback.props = {
#                node.name              = "EQ-crinacle-GRAS-43AG-7"
#             }
#             capture.props = {
#                node.name              = "EQ-crinacle-GRAS-43AG-7"
#             }
#         }
#     },
#     {
#         name = libpipewire-module-parametric-equalizer
#         args = {
#             remote.name            = "pipewire-0"
#             equalizer.filepath     = "/home/blu/git/mainrig-MS-7D51/.config/pipewire/pipewire.conf.d/EQ/HD800S/HD 800 S EQ oratory1990 GRAS 45-BC"
#             equalizer.description  = "HD 800 S EQ oratory1990 GRAS 45-BC"
#             audio.channels         = 2
#             audio.position         = [ FL, FR ]
#             playback.props = {
#                 node.name              = "EQ-oratory-GRAS-45-BC"
#             }
#             capture.props = {
#                 node.name              = "EQ-oratory-GRAS-45-BC"
#             }
#         }
#     },
#     {
#         name = libpipewire-module-parametric-equalizer
#         args = {
#             remote.name            = "pipewire-0"
#             equalizer.filepath     = "/home/blu/git/mainrig-MS-7D51/.config/pipewire/pipewire.conf.d/EQ/DT770/DT 770 Pro EQ crinacle GRAS 43AG-7"
#             equalizer.description  = "DT 770 Pro EQ crinacle GRAS 43AG-7"
#             audio.channels         = 2
#             audio.position         = [ FL, FR ]
#             playback.props = {
#                 node.name              = "EQ-DT770-crinacle"
#             }
#             capture.props = {
#                 node.name              = "EQ-DT770-crinacle"
#             }
#         }
#     }
# ]
