SCRIPT_DIR=/home/blu/.local/libexec/i3blocks

[cpu]
interval=3
color=#ffffff
#border=#268BD2
border=#2AA198
border_right=0
border_left=0
border_top=0
border_bottom=1
markup=pango
command=bash ./scripts/cpu-levels.bash

[inet]
interval=1
command=bash ./scripts/check_network.bash
markup=pango

[weather]
interval=640
command=curl "wttr.in/Wiesloch?format=3"

[holiday]
interval=360
command=./scripts/holiday.sh
color=#FFD4B2
markup=pango

[battery]
interval=1
command=./scripts/batt-estimate.sh
color=#FFDF00

[air]
interval=640
command= bash ./scripts/air.sh

[calendar]
command=$SCRIPT_DIR/calendar
interval=1
LABEL=   
DATEFMT=+%a %Y-%m-%d %H:%M:%S
# SHORTFMT=+%H:%M:%S
color=#FF8A65

