SCRIPT_DIR=/home/blu/.local/libexec/i3blocks

[hostname]
interval=60
command=hostname
markup=pango
color=#0AA0EF

#[display]
#interval=60
#command=echo "HDMI-A-0 -L "

# [nvme-temps]
# interval=3
# command=sensors -j | jq -r '(.["nvme-pci-0100"]["Adapter"] + ": " + (.["nvme-pci-0100"]["Composite"]["temp1_input"]|tostring) + "°C, " + .["nvme-pci-3000"]["Adapter"] + ": " + (.["nvme-pci-3000"]["Composite"]["temp1_input"]|tostring) + "°C") | gsub("PCI adapter"; "nvme0n1") | gsub("nvme0n1 Temperature"; "nvme1n1 Temperature")'

# [nvme-temp-nvme1n1]
# interval=3
# command=sensors -j | jq '"nvme1n1 \(.["nvme-pci-3000"]["Composite"]["temp1_input"])°C"'

[ipinfo]
command=curl -s ipinfo.io | jq .org
interval=60
color=#F979FF

[vpn-location-mullvad]
command=mullvad status | grep -o 'in .*' | cut -d' ' -f3-
interval=60
color=#FFF000

[calendar]
command=$SCRIPT_DIR/calendar
interval=1
LABEL=  -
DATEFMT=+%Y-%m-%d %H:%M:%S
# SHORTFMT=+%H:%M:%S
color=#FF8A65

