# i3 Configuration File - Window Keybinds

$bm $meta+e layout toggle split
$bm $meta+s layout stacking
$bm $meta+t layout tabbed
$bm $meta+f fullscreen toggle

# $bm $meta+Shift+c $mpc 

$bm $meta+Down focus down
$bm $meta+Left focus output left
$bm $meta+Right focus output right
$bm $meta+Up focus up

$bm $meta+Shift+a $mctw next
$bm $meta+Shift+d $rs 192px 108px,$map 698px 27px,focus output right
$bm $meta+Shift+Down $md, focus down
$bm $meta+Shift+g $rs 1280px 1024px, $map 1400px 371px
$bm $meta+Shift+Left $mtol, focus output left
$bm $meta+Shift+p $ensi ~/.config/sway/halt-continue.sh toggle
$bm $meta+Shift+Right $mtor, focus output right
$bm $meta+Shift+space floating toggle
$bm $meta+Shift+Up $mu, focus up
$bm $meta+Space focus mode_toggle

$bm $meta+v split v
$bm Control+q kill
$bm Menu+Control+Down $md, focus down
$bm Menu+Control+Left $mtol, focus output left
$bm Menu+Control+Right $mtor, focus output right
$bm Menu+Control+space floating toggle
$bm Menu+Control+Up $mu, focus up
$bm Menu+Left $fl
$bm Menu+Right focus output right
$bm Menu+Up focus up
# /home/blu/.config/sway/killscript.sh
# back and forth
$bm $meta+Tab $ws back_and_forth 

# These are i3 specific and will only be recognized and be usable in i3

# set $meta Mod4
# set $alt Mod1

# Previous workspace group
$bm $meta+KP_0 $ensi ~/.config/sway/ws-switch.sh prev
$bm Control+KP_0 $ensi ~/.config/sway/ws-switch.sh prev
$bm $alt+KP_0 $ensi ~/.config/sway/ws-switch.sh prev

# Next workspace group
$bm Control+KP_Decimal $ensi ~/.config/sway/ws-switch.sh next
$bm $meta+KP_Decimal $ensi ~/.config/sway/ws-switch.sh next
$bm $alt+KP_Decimal $ensi ~/.config/sway/ws-switch.sh next

# Control + numpad
$bm Control+KP_1 exec swaymsg '$ws 2, $ws 1, $ws 4, $ws 3'    
$bm Control+KP_2 exec swaymsg '$ws 6, $ws 5, $ws 8, $ws 7'    
$bm Control+KP_3 exec swaymsg '$ws 10, $ws 9, $ws 12, $ws 11'
$bm Control+KP_4 exec swaymsg '$ws 14, $ws 13, $ws 16, $ws 15'
$bm Control+KP_5 exec swaymsg '$ws 18, $ws 17, $ws 20, $ws 19'
$bm Control+KP_6 exec swaymsg '$ws 22, $ws 21, $ws 24, $ws 23'
$bm Control+KP_7 exec swaymsg '$ws 26, $ws 25, $ws 28, $ws 27'
$bm Control+KP_8 exec swaymsg '$ws 30, $ws 29, $ws 32, $ws 31'
$bm Control+KP_9 exec swaymsg '$ws 34, $ws 33, $ws 36, $ws 35'

# Meta + numpad
$bm $meta+KP_1 exec swaymsg '$ws 38, $ws 37, $ws 40, $ws 39'
$bm $meta+KP_2 exec swaymsg '$ws 42, $ws 41, $ws 44, $ws 43'
$bm $meta+KP_3 exec swaymsg '$ws 46, $ws 45, $ws 48, $ws 47'
$bm $meta+KP_4 exec swaymsg '$ws 50, $ws 49, $ws 52, $ws 51'
$bm $meta+KP_5 exec swaymsg '$ws 54, $ws 53, $ws 56, $ws 55'
$bm $meta+KP_6 exec swaymsg '$ws 58, $ws 57, $ws 60, $ws 59'
$bm $meta+KP_7 exec swaymsg '$ws 62, $ws 61, $ws 64, $ws 63'
$bm $meta+KP_8 exec swaymsg '$ws 66, $ws 65, $ws 68, $ws 67'
$bm $meta+KP_9 exec swaymsg '$ws 70, $ws 69, $ws 72, $ws 71'

# Alt + numpad exec swaymsg '+KP_1  exec swaymsg '$ws 74, $ws 73, $ws 76, $ws 75'
$bm $alt+KP_2  exec swaymsg '$ws 78, $ws 77, $ws 80, $ws 79'
$bm $alt+KP_3  exec swaymsg '$ws 82, $ws 81, $ws 84, $ws 83'
$bm $alt+KP_4  exec swaymsg '$ws 86, $ws 85, $ws 88, $ws 87'
$bm $alt+KP_5  exec swaymsg '$ws 90, $ws 89, $ws 92, $ws 91'
$bm $alt+KP_6  exec swaymsg '$ws 94, $ws 93, $ws 96, $ws 95'
$bm $alt+KP_7  exec swaymsg '$ws 98, $ws 97, $ws 100, $ws 99'
$bm $alt+KP_8  exec swaymsg '$ws 102, $ws 101, $ws 104, $ws 103'
$bm $alt+KP_9  exec swaymsg '$ws 106, $ws 105, $ws 108, $ws 107'

# scratchpad
$bm $meta+Shift+minus move scratchpad
$bm $meta+equal scratchpad show

$bm $meta+x exec 'swaymsg sticky toggle'