$bm { 
    # Workspace Switching (Alt + KP)
    $alt+KP_0 $ensi ~/.config/sway/scripts/ws-switch.sh prev
    $alt+KP_1 exec swaymsg 'workspace 109, workspace 110, workspace 111, workspace 112, workspace 113, workspace 111'
    $alt+KP_2 exec swaymsg 'workspace 113, workspace 114, workspace 115, workspace 116, workspace 117, workspace 117'
    $alt+KP_3 exec swaymsg 'workspace 119, workspace 120, workspace 121, workspace 122, workspace 123, workspace 123'
    $alt+KP_4 exec swaymsg 'workspace 125, workspace 126, workspace 127, workspace 128, workspace 129, workspace 129'
    $alt+KP_5 exec swaymsg 'workspace 131, workspace 132, workspace 133, workspace 134, workspace 135, workspace 135'
    $alt+KP_6 exec swaymsg 'workspace 137, workspace 138, workspace 139, workspace 140, workspace 141, workspace 141'
    $alt+KP_7 exec swaymsg 'workspace 143, workspace 144, workspace 145, workspace 146, workspace 147, workspace 147'
    $alt+KP_8 exec swaymsg 'workspace 149, workspace 150, workspace 151, workspace 152, workspace 153, workspace 153'
    $alt+KP_9 exec swaymsg 'workspace 155, workspace 156, workspace 157, workspace 158, workspace 159, workspace 159'
    $alt+KP_Decimal $ensi ~/.config/sway/scripts/ws-switch.sh next

    # Resizing (Meta + Ctrl)
    $meta+Ctrl+Down resize shrink height 1 px or 1 ppt
    $meta+Ctrl+Left resize grow width 1 px or 1 ppt
    $meta+Ctrl+Right resize shrink width 1 px or 1 ppt
    $meta+Ctrl+Up resize grow height 1 px or 1 ppt

    # Navigation & Layout
    $meta+Down focus down
    $meta+e layout toggle split
    $meta+equal scratchpad show
    $meta+f fullscreen toggle
    $meta+KP_0 $ensi ~/.config/sway/scripts/ws-switch.sh prev
    $meta+KP_1 exec swaymsg 'workspace 55, workspace 56, workspace 58, workspace 59, workspace 60, workspace 57'
    $meta+KP_2 exec swaymsg 'workspace 61, workspace 62, workspace 64, workspace 65, workspace 66, workspace 63'
    $meta+KP_3 exec swaymsg 'workspace 67, workspace 68, workspace 70, workspace 71, workspace 72, workspace 69'
    $meta+KP_4 exec swaymsg 'workspace 73, workspace 74, workspace 76, workspace 77, workspace 78, workspace 75'
    $meta+KP_5 exec swaymsg 'workspace 79, workspace 80, workspace 82, workspace 83, workspace 84, workspace 81'
    $meta+KP_6 exec swaymsg 'workspace 85, workspace 86, workspace 88, workspace 89, workspace 90, workspace 87'
    $meta+KP_7 exec swaymsg 'workspace 91, workspace 92, workspace 94, workspace 95, workspace 96, workspace 93'
    $meta+KP_8 exec swaymsg 'workspace 97, workspace 98, workspace 100, workspace 101, workspace 102, workspace 99'
    $meta+KP_9 exec swaymsg 'workspace 103, workspace 104, workspace 106, workspace 107, workspace 108, workspace 105'
    $meta+KP_Decimal $ensi ~/.config/sway/scripts/ws-switch.sh next

    # Output Focus (Meta)
    $meta+Left focus output left
    $meta+Right focus output right
    $meta+s layout stacking

    # Miscellaneous (Meta + Shift)
    $meta+Shift+a $mctw next
    $meta+Shift+d $rs 192px 108px,$map 698px 27px,focus output right
    $meta+Shift+Down $md, focus down
    $meta+Shift+g $rs 1280px 1024px, $map 1400px 371px
    $meta+Shift+Left $mtol, focus output left
    $meta+Shift+minus move scratchpad
    $meta+Shift+p $ensi ~/.config/sway/scripts/halt-continue.sh toggle
    $meta+Shift+Right $mtor, focus output right
    $meta+Shift+space floating toggle
    $meta+Shift+Up $mu, focus up
    $meta+space focus mode_toggle
    $meta+t layout tabbed
    $meta+Tab workspace back_and_forth
    $meta+Up $fu
    $meta+v split v
    $meta+x exec 'swaymsg sticky toggle'

    # Miscellaneous (Control)
    Control+q kill

    # Menu Focus (Menu + Control)
    Menu+Control+Down $md, focus down
    Menu+Control+Left $mtol, focus output left
    Menu+Control+Right $mtor, focus output right
    Menu+Control+space floating toggle
    Menu+Control+Up $mu, focus up

    # Navigation (Menu)
    Menu+Left $fl
    Menu+Right $fr
    Menu+Up $fu
}
