# i3 Configuration File - Application Shortcuts

# Open Dolphin file manager
$bm $meta+n $ensi dolphin

# Capture entire screen
$bm Print $ensi grim ~/Pictures/screenshot.png

# Capture entire screen to clipboard
$bm Ctrl+Print $ensi grim - | wl-copy

# Capture selected region to clipboard
$bm Ctrl+Shift+Print $ensi grim -g "$(slurp)" - | wl-copy

# Capture selected region with a unique name
$bm Shift+Print $ensi grim ~/Pictures/screenshot-$(date +'%Y-%m-%d-%H%M%S').png -g "$(slurp)"

# Capture active window
$bm $meta+Print $ensi grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? == true) | .rect | "\(.x),\(.y) \(.width)x\(.height)")" ~/Pictures/screenshot.png

# Capture active window to clipboard
$bm Ctrl+$meta+Print $ensi grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? == true) | .rect | "\(.x),\(.y) \(.width)x\(.height)")" - | wl-copy


# 191 => G1 (F13)
# 192 => G2 (F14)
# 193 => G3 (F15)
# 194 => G4 (F16)
# 195 => G5 (F17)
# 196 => G6 (F18)

# OCR
    $bc 191 $ensi ~/.config/sway/GKeys/G1-ocr-en.sh
# CC
    $bc 192 $ensi ~/.config/sway/GKeys/G2-capturecard.sh
    $bc 194 $ensi ~/.config/sway/GKeys/G4-triple-click-copy.sh
    # $bc 194 $ensi swaymsg output DisplayPort-1 mode 1920x1080@240Hz position 1080 1080
    # $bc 195 $ensi swaymsg output DisplayPort-1 mode 1920x1080@48Hz position 1080 1080

    $bc 196 $ensi swaylock

# Open alacritty terminal
$bm $meta+Return $ensi alacritty
$bm Menu+Return $ensi alacritty
$bm Menu+KP_ENTER $ensi alacritty

# Reload i3 config and i3blocks
$bm $meta+Shift+c reload
$bm $meta+Shift+b $ensi ~/.config/sway/i3blocksreload.sh

# Restart i3
$bm $meta+Shift+r restart

# Launch Rofi app launcher
# $bm Control+e $ensi rofi -show drun
$bm Control+e $ensi wofi --show=drun -Dlayer=overlay

# # Cycle through Windows
#$bm $meta+d $e rofi -show window

bindsym $meta+d exec swayr switch-window
# bindsym $mod+Delete      exec swayr quit-window
# bindsym $mod+Tab         exec swayr switch-to-urgent-or-lru-window
# bindsym $mod+Next        exec swayr next-window all-workspaces
# bindsym $mod+Prior       exec swayr prev-window all-workspaces
# bindsym $mod+Shift+Space exec swayr switch-workspace-or-window
# bindsym $mod+c           exec swayr execute-swaymsg-command
# bindsym $mod+Shift+c     exec swayr execute-swayr-command

$bm CTRL+F2 exec swaymsg '[class="Mullvad Browser"] focus'

