# sway Configuration File - Application Shortcuts
$bm { 
    # Navigation
        # Open Dolphin file manager
        $meta+n $ensi dolphin

        # Wofi + Swayr 
        Control+e $ensi wofi --show=drun --location=center --width=800px --height=800px -Dlayer=overlay

        #$meta+d $ensi python ~/.config/sway/scripts/wofi-app-switcher.py
        

        $meta+d exec swayr switch-window

    # Screenshots
        # Capture entire screen
        Print $ensi grim ~/Pictures/screenshot.png
        # Capture entire screen to clipboard
        Ctrl+Print $ensi grim - | wl-copy
        # Capture selected region to clipboard
        Ctrl+Shift+Print $ensi grim -g "$(slurp)" - | wl-copy
        # Capture selected region with a unique name
        Shift+Print $ensi grim ~/Pictures/screenshot-$(date +'%Y-%m-%d-%H%M%S').png -g "$(slurp)"

        # Capture active window
        $meta+Print $ensi grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? == true) | .rect | "\(.x),\(.y) \(.width)x\(.height)")" ~/Pictures/screenshot.png

        # Capture active window to clipboard
        Ctrl+$meta+Print $ensi grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? == true) | .rect | "\(.x),\(.y) \(.width)x\(.height)")" - | wl-copy

    # Terminal
        # Open alacritty terminal
        $meta+Return $ensi alacritty
        Menu+Return $ensi alacritty
        Menu+KP_ENTER $ensi alacritty

    # Sway
        # Reload sway config and i3blocks
        $meta+Shift+c exec "swaymsg reload; exec ~/.config/sway/scripts/i3blocksreload.sh"

        # Restart sway
        $meta+Shift+r restart
}


# Gamepad Shortcuts (F23, F24)
$bc {
    201 exec swaymsg '[$c="Slippi Launcher"] focus' && swaymsg '[$t="^Faster Melee - Slippi \(\d+\.\d+\.\d+\)$"] focus'
    202 exec swaymsg workspace 1, workspace 2, workspace 3, workspace 4;  swaymsg '[$c="Slippi Launcher"] focus'
}
