# sway Configuration File - Applications Autostart
$ensi /usr/bin/code-server --auth none
$ensi /usr/bin/kdenlive
$ensi /usr/bin/mdbook serve /mnt/n/iOS-Accessibility-Guide -p 3000 -n 0.0.0.0
$ensi /usr/bin/nvtop
$ensi /usr/bin/steam-native -no-browser
$ensi /usr/lib/xdg-desktop-portal -r
$ensi ~/.config/sway/scripts/alacritty-micro-stickies/startup.sh
$ensi ~/.config/sway/scripts/set-firefox-mappings-handlr.sh
$ensi ~/apps/slippi/./Slippi.AppImage --no-sandbox
$ensi ~/cxoffice/bin/crossover
$ensi ~/scripts/autostart/script-startup.sh
$ensi ~/scripts/cronjobs/watch-borgbackup-log.sh
$ensi akonadictl stop
$ensi antimicrox --hidden
$ensi code # vscode
$ensi corectrl
$ensi dex --autostart --environment sway
$ensi env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1
$ensi fcitx5 -d
$ensi keepassxc
$ensi mako
$ensi mullvad connect
$ensi thunderbird
$ensi wire-desktop 
$ensi wlsunset -l 49.3000 -L 8.7000
$ensi autostart/start_keyboard-watcher.sh