# sway Configuration File - Applications Autostart
$e {
    /usr/bin/code-server --auth none
    /usr/bin/kdenlive
    /usr/bin/mdbook serve /mnt/n/iOS-Accessibility-Guide -p 3000 -n 0.0.0.0
    /usr/bin/nvtop
    /usr/bin/steam-native -no-browser
    /usr/lib/xdg-desktop-portal -r
    ~/.config/sway/scripts/alacritty-micro-stickies/startup.sh
    ~/.config/sway/scripts/set-firefox-mappings-handlr.sh
    ~/apps/slippi/./Slippi.AppImage --no-sandbox
    ~/cxoffice/bin/crossover
    ~/scripts/autostart/script-startup.sh
    ~/scripts/cronjobs/watch-borgbackup-log.sh
    akonadictl stop
    antimicrox --hidden
    code # vscode
    corectrl
    dex --autostart --environment sway
    env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1
    fcitx5
    fcitx5 -d
    keepassxc
    mako
    mullvad connect
    sleep 10 && ~/.config/sway/scripts/remove-urgent-marks.sh
    thunderbird
    wire-desktop 
    wlsunset -l 49.3000 -L 8.7000
}

