# sway Configuration File - Applications Autostart

# exec mscore # musescore
# exec --no-startup-id --no-startup-id dunst # for inotify-send etc
exec mako # for inotify-send etc
exec akonadictl stop
# && /home/blu/scripts/suspend-and-speaker-off.sh

# watch borgbackups
exec /home/blu/scripts/cronjobs/watch-borgbackup-log.sh

# exec ~/apps/slippi/./Slippi.AppImage
exec ~/cxoffice/bin/crossover
# exec ~/jd2/JDownloader2

exec ~/scripts/autostart/script-startup.sh
# exec alacritty --class=alacritty-trackma-curses -e trackma-curses 

# exec bash ~/.config/sway/unfocused-window-mute.sh
# exec bash ~/.config/sway/unfocused-window-stopper.sh
exec code # vscode
exec dex --autostart --environment sway
exec fcitx5 -d
# exec lxqt-policykit-agent

# exec GDK_SCALE=2 fsearch # for making fsearch font double as large
# exec idea # IntelliJ IDEA 
exec corectrl
# exec ckb-next
exec keepassxc
exec mullvad connect
#exec mullvad-browser -P mullvadbrowser-real-debrid --class="mullvadbrowser-real-debrid"
# exec numlockx
# exec obsidian
# exec parallel-launcher
# exec python3 ~/broadlink/broadlink_ui.py 
# exec ssh -L 5000:127.0.0.1:5000 -N root@tail.ws -p 764

# exec syncthing
exec thunderbird
# exec virt-manager
exec wire-desktop 

# disabled ... wanna be sway compatible.
#exec --no-startup-id picom --config ~/.config/picom/picom.conf

exec env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1
exec sleep 10 && /home/blu/.config/sway/scripts/remove-urgent-marks.sh

# exec /home/blu/.config/sway/cardcapture-behavior.sh
exec antimicrox --hidden
# exec sleep 10 && swaymsg restart
# make sure firefox mappings for xdg are kept
exec ~/.config/sway/scripts/set-firefox-mappings-handlr.sh
# exec sleep 30 && ~/.config/sway/i3blocksreload.sh
exec fcitx5
# for screenrecordings etc
exec /usr/lib/xdg-desktop-portal -r
exec /home/blu/.config/sway/scripts/alacritty-micro-stickies/startup.sh
exec /usr/bin/kdenlive
exec /usr/bin/code-server --auth none
exec /usr/bin/mdbook serve /mnt/n/iOS-Accessibility-Guide -p 3000 -n 0.0.0.0
exec /usr/bin/steam -no-browser
exec /usr/bin/nvtop

# Wiesloch / Gamma 
exec wlsunset -l 49.3000 -L 8.7000

