# sway Configuration File - general window rules

$fw [$a="^Mullvad VPN$"] move to scratchpad
$fw [$a="alacritty-time"] $mtw 1, $fe, $rs 247px 247px, $map 832px 1671px
$fw [$a="Alacritty"] border pixel 1
$fw [$a="code-oss"] $mto $M, focus
$fw [$a="com.github.wwmm.easyeffects"] move to scratchpad, scale 0.7
$fw [$a="mpvfloattopright"] $mtw 2, $fe, $mr 440, $mu 890, border none, opacity 1
$fw [$a="mpvleft"] $mto $L, $md, $f, $bp0
$fw [$a="mpvright"] $mto $R, $fs
$fw [$a="org.kde.okular"] $fe
$fw [$a="org.pulseaudio.pavucontrol"] $fe, $rs 1024px 768px
$fw [$a="playlist-th"] $mto $L, $f, $bp0
$fw [$a="SVPManager"] $fe, $rs 1916px 1029px, $map 1081px 380px
$fw [$a="xfce-polkit"] $fe
$fw [$c="[aA]lacritty"] $f
$fw [$c="[cC]ode"] $mto $M, focus
$fw [$c="[kK]ate"] $fe, $rs 1020 1060
$fw [$c="[xX]fce4-terminal"] $f
$fw [$c="^adi2remote.exe$"] $fe
$fw [$c="^ColorPicker$"] $fe
$fw [$c="^EtG.x86_64$"] $fe
$fw [$c="^GParted$"] $fe
$fw [$c="^net-filebot-Main$"] $fe, $map 1080px 340px
$fw [$c="^tw-com-aten-ikvm-KVMMain$"] $fe, $rs 1280px 1024px
$fw [$c="code-oss"] $mto $M, focus
$fw [$c="explorer.exe"] $mts
$fw [$c="kalgebra"] $fe
$fw [$c="kdenlive"] $fe
# $fw [$c="Pianoteq"] floating enable, move to scratchpad
$fw [$c="th19.exe"] $fe, border none
$fw [$c="xfce-polkit"] $f
$fw [$c="Yad"] $fe
$fw [$i="mpvcapturecard-secondary"] $mto $RR
$fw [$i="mpvcapturecard"] $mtw 54
$fw [$i="vscodium"] $mto $M, focus
$fw [$t="^/dev/video0$"] $mtw 53, $fs
$fw [$t="^/dev/video1$"] $mtw 54, $fs
$fw [$t="^Chat with Amazon Customer Service ー Mozilla Firefox$"] $fe, $rs 400px 400px
$fw [$t="^Cultris II$"] $fe, $mpc
$fw [$t="^File Upload$"] $rs 1024px 768px, $mpc, $f
$fw [$t="^Go to Home - iOS Accessibility Testing Guide — Mullvad Browser$"] $mtw 2, $fe, $rs 1916px 1029px, $map 1081px 380px
$fw [$t="^Interactive display adjustment$"] $mtw 1, $fe, $rs 1916px 1029px, $map 1081px 380px

$fw [shell="xwayland"] title_format '%title 𝓧'

$fw [$a="^alacritty-micro-cursor-*$"] floating enable

$fw [$a="^alacritty-micro-startup-intake$"] $mtw $ws01-R, splitv, layout toggle split
$fw [$a="^alacritty-micro-startup-wellbeing$"] $mtw $ws01-R, splith, layout toggle split

$fw [$a="^alacritty-micro-startup-wanikani-cheat$"] $mtw $ws08-M, splith

