$bc {
    196 $ensi '/home/blu/.config/sway/tripleclick.sh' &&  < "/home/blu/.config/sway/bitv-copy-click-translate.txt" dotoolc
} 
$bm {
    $meta+F12 $ensi echo type $(wl-paste) | dotool
    $meta+F10 $ensi < "/home/blu/.config/sway/bitv-template.txt" dotool
} 







