bindsym F1 exec echo "key ctrl+c" | dotool && swaymsg '[app_id="io.github.cboxdoerfer.FSearch"] focus' && echo "key ctrl+a" | dotool && echo "key ctrl+v" | dotool

bindsym $meta+F12 exec echo type $(wl-paste) | dotool

bindsym $meta+F10 exec < "/home/blu/.config/sway/bitv-template.txt" dotool

bindsym $meta+Home exec echo type $(date '+%a %Y-%m-%d') | dotool

bindcode 196 exec '/home/blu/.config/sway/tripleclick.sh' &&  < "/home/blu/.config/sway/bitv-copy-click-translate.txt" dotoolc





