$bc {
    196 exec '/home/blu/.config/sway/tripleclick.sh' &&  < "/home/blu/.config/sway/bitv-copy-click-translate.txt" dotoolc
} 
$bm {
    $meta+F12 exec echo type $(wl-paste) | dotool
    $meta+F10 exec < "/home/blu/.config/sway/bitv-template.txt" dotool
} 







