bindsym F1 exec echo "key ctrl+c" | dotool && swaymsg '[app_id="io.github.cboxdoerfer.FSearch"] focus' && echo "key ctrl+a" | dotool && echo "key ctrl+v" | dotool

bindsym $meta+F12 exec echo type $(wl-paste) | dotool

bindsym $meta+F11 exec < "/home/blu/.config/sway/bitv-what-why-how.txt" dotool
bindsym $meta+F10 exec < "/home/blu/.config/sway/bitv-categorization.txt" dotool

bindsym $meta+Home exec echo type $(date '+%a %Y-%m-%d') | dotool
# bindsym F1 exec dotoold & (echo "key ctrl+c" && swaymsg '[app_id="io.github.cboxdoerfer.FSearch"] focus' && echo "key ctrl+a" && echo "key ctrl+v") | dotoolc