# $bm $meta+XF86AudioMute $ensi broadlink_cli --device @/home/blu/broadlink/BEDROOM.device --send @/home/blu/broadlink/RME/ADI2-DAC-FS/RME-switch-headphone-speaker
$bm XF86AudioLowerVolume $ensi wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
$bm XF86AudioMicMute $ensi wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
$bm XF86AudioMute $ensi wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

$bm XF86AudioRaiseVolume $ensi wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+

# mpv control
$bm XF86AudioNext $ensi ~/.config/sway/mediacontrol.sh mpv-next
$bm XF86AudioPlay $ensi ~/.config/sway/mediacontrol.sh mpv-pause
$bm XF86AudioPrev $ensi ~/.config/sway/mediacontrol.sh mpv-prev
$bm XF86AudioStop $ensi ~/.config/sway/mediacontrol.sh mpv-stop

# playerctl control
$bm $meta+XF86AudioNext $ensi ~/.config/sway/mediacontrol.sh playerctl-next
$bm $meta+XF86AudioPlay $ensi ~/.config/sway/mediacontrol.sh playerctl-play-pause
$bm $meta+XF86AudioPrev $ensi ~/.config/sway/mediacontrol.sh playerctl-prev
$bm $meta+XF86AudioStop $ensi ~/.config/sway/mediacontrol.sh playerctl-stop

# to control archm1 (3=alt)
# $bm $alt+XF86AudioRaiseVolume $ensi ssh blu@192.168.178.31 "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
# $bm $alt+XF86AudioLowerVolume $ensi ssh blu@192.168.178.31 "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
# $bm $alt+XF86AudioMute $ensi ssh blu@192.168.178.31 "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
# $bm $alt+XF86AudioMicMute $ensi ssh blu@192.168.178.31 "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
# $bm $alt+XF86AudioNext $ensi ssh blu@192.168.178.31 "playerctl next"
# $bm $alt+XF86AudioPlay $ensi ssh blu@192.168.178.31 "playerctl pause"
# $bm $alt+XF86AudioPlay $ensi ssh blu@192.168.178.31 "playerctl play"
# $bm $alt+XF86AudioPrev $ensi ssh blu@192.168.178.31 "playerctl previous"
# $bm $alt+XF86AudioStop $ensi ssh blu@192.168.178.31 "playerctl play-pause"