### microstickies

set $microstickies "/home/blu/.config/sway/alacritty-dedicated/alacritty-micro.sh"
bindsym $meta+c exec $microstickies blue

mode "ncolor" {

bindsym     1       exec     $microstickies        blue
bindsym     2       exec     $microstickies        orange
bindsym     3       exec     $microstickies        purple

    # Return to default mode
bindsym Return mode "default"
bindsym Escape mode "default"
}
bindsym F11 mode "ncolor"

##################