### microstickies

set $microstickies "/home/blu/.config/sway/alacritty-micro-stickies/micro-stickies.sh"
$bm $meta+c exec $microstickies blue --cursor

# mode "ncolor" {

# $bm     1       exec     $microstickies        blue
# $bm     2       exec     $microstickies        orange
# $bm     3       exec     $microstickies        purple
# $bm     4       exec     $microstickies        green
# $bm     5       exec     $microstickies        red
# $bm     9       exec     $microstickies        transparent

#     # Return to default mode
# $bm Return mode "default"
# $bm Escape mode "default"
# }
# $bm F11 mode "ncolor"

##################44C