### microstickies

set $microstickies "/home/blu/.config/sway/alacritty-micro-stickies/micro-stickies.sh"
bindsym $meta+c exec $microstickies blue --cursor

mode "ncolor" {

bindsym     1       exec     $microstickies        blue
bindsym     2       exec     $microstickies        orange
bindsym     3       exec     $microstickies        purple
bindsym     4       exec     $microstickies        green
bindsym     5       exec     $microstickies        red
bindsym     9       exec     $microstickies        transparent

    # Return to default mode
bindsym Return mode "default"
bindsym Escape mode "default"
}
bindsym F11 mode "ncolor"

##################44C