 # Creates silent stream... with easyeffects
 # see https://github.com/wwmm/easyeffects/issues/2938
exec /home/blu/.config/sway/fix-easy-effects.sh

# load EQ preset for Headphones
exec easyeffects --load-preset "[crinacle] GRAS 43AG-7 Sennheiser HD 800 S"
