# bindsym $meta+m 'output * toggle'
bindsym $meta+m exec swaymsg -t get_outputs | jq -r '.[].name' | xargs -I{} swaymsg output {} disable
bindsym $meta+comma exec swaymsg -t get_outputs | jq -r '.[].name' | xargs -I{} swaymsg output {} enable
