# sway Configuration File - Applications Autostart

#$e mscore # musescore
# $e --no-startup-id --no-startup-id dunst # for inotify-send etc
$e mako # for inotify-send etc
$e akonadictl stop
$e xautolock -time 600 -locker "xset dpms force off" -notify 30 -notifier "notify-send 'Idle for 60 minutes'" 
# && /home/blu/scripts/suspend-and-speaker-off.sh

# watch borgbackups
$e /home/blu/scripts/cronjobs/watch-borgbackup-log.sh

# $e ~/apps/slippi/./Slippi.AppImage
$e ~/cxoffice/bin/crossover
# $e ~/jd2/JDownloader2

$e ~/scripts/autostart/script-startup.sh
$e alacritty --class=alacritty-trackma-curses -e trackma-curses 

# $e bash ~/.config/sway/unfocused-window-mute.sh
# $e bash ~/.config/sway/unfocused-window-stopper.sh
$e code # vscode
$e dex --autostart --environment sway
$e fcitx5 -d
# $e lxqt-policykit-agent

$e GDK_SCALE=2 fsearch # for making fsearch font double as large
# $e idea # IntelliJ IDEA 
$e corectrl
# $e ckb-next
$e keepassxc
$e mullvad connect
#$e mullvad-browser -P mullvadbrowser-real-debrid --class="mullvadbrowser-real-debrid"
$e numlockx
$e obsidian
# $e parallel-launcher
# $e python3 ~/broadlink/broadlink_ui.py 
# $e ssh -L 5000:127.0.0.1:5000 -N root@tail.ws -p 764
# $e steam
# $e syncthing
$e thunderbird
# $e virt-manager
$e wire-desktop 

# disabled ... wanna be sway compatible.
#$e --no-startup-id picom --config ~/.config/picom/picom.conf

$e env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd > /tmp/swayrd.log 2>&1
$e sleep 10 && /home/blu/.config/sway/remove-urgent-marks.sh

# $e /home/blu/.config/sway/cardcapture-behavior.sh
$e antimicrox --hidden
# $e sleep 10 && swaymsg restart
# make sure firefox mappings for xdg are kept
$e ~/.config/sway/set-firefox-mappings-handlr.sh
# $e sleep 30 && ~/.config/sway/i3blocksreload.sh
$e fcitx5
# for screenrecordings etc
$e /usr/lib/xdg-desktop-portal -r
