
# sway Configuration File - general window rules

$fw [$a="mpvfloattopright"] $mtw 1, $fe, $mr 440, $mu 890, border none
$fw [$a="mpvleft"] $mto $L, $md, $f, $bp0
$fw [$a="mpvright"] $mto $R, $md, $f, $fs, $bp0
$fw [$a="org.pulseaudio.pavucontrol"] $fe, $rs 1024px 768px
$fw [$a="playlist-th"] $mto $L, $f, $bp0
$fw [$a="xfce-polkit"] $fe
$fw [$c="[aA]lacritty"] $f
$fw [$c="[kK]ate"] $fe, $rs 1020 1060
$fw [$c="[xX]fce4-terminal"] $f
$fw [$c="^adi2remote.exe$"] $fe
$fw [$c="^ColorPicker$"] $fe
$fw [$c="^EtG.x86_64$"] $fe
$fw [$c="^GParted$"] $fe
$fw [$c="^net-filebot-Main$"] $fe, $map 1080px 340px
$fw [$c="^tw-com-aten-ikvm-KVMMain$"] $fe, $rs 1280px 1024px
$fw [$c="explorer.exe"] $mts
$fw [$c="kalgebra"] $fe
$fw [$c="kdenlive"] $fe
$fw [$c="th19.exe"] $fe, border none
$fw [$c="xfce-polkit"] $f
$fw [$c="Yad"] $fe
$fw [$i="mpvcapturecard-secondary"] $mto $RR
$fw [$i="mpvcapturecard"] $mtw 54
$fw [$t="^/dev/video0$"] $mtw 53, $fs
$fw [$t="^/dev/video1$"] $mtw 54, $fs
$fw [$t="^Cultris II$"] $fe, $mpc
$fw [$t="^File Upload$"] $rs 1024px 768px, $mpc, $f
$fw [$t="^Go to Home - iOS Accessibility Testing Guide — Mullvad Browser$"] $mtw 2, $fe, $rs 1916px 1029px, $map 1081px 380px
$fw [$t="^Interactive display adjustment$"] $mtw 1, $fe, $rs 1916px 1029px, $map 1081px 380px