
# i3 Configuration File - general window rules
$fw [$c="[aA]lacritty"] focus
$fw [$c="kdenlive"] floating enable
$fw [$c="[kK]ate"] $fe, $rs 1020 1060
$fw [$c="[xX]fce4-terminal"] focus
$fw [$c="^adi2remote.exe$"] floating enable
$fw [$c="^ColorPicker$"] floating enable
$fw [$c="^EtG.x86_64$"] floating enable
$fw [$c="^GParted$"] floating enable
$fw [$c="explorer.exe"] $mts
$fw [$c="kalgebra"] $fe
$fw [$c="Pavucontrol"] $fe
$fw [$c="th19.exe"] $fe, border none
$fw [$c="xfce-polkit"] focus
$fw [$c="Yad"] $fe
$fw [$i="mpvcapturecard-secondary"] $mto $RR
$fw [$i="mpvcapturecard"] $mtw 54
#$fw [$i="mpvfloattopright"] $mtw 1, $fe, $map 890px 27px, $rs 192px 108px, focus, border none
$fw [$a="mpvfloattopright"] $mtw 1, $fe, move right 440, move up 890, border none
$fw [$a="mpvleft"] $mto $L, move down, focus, $bp0

#$fw [$c="wofi"] floating enable, border none, focus, move position center, sticky enable, always_on_top enable

$fw [$a="mpvright"] $mto $R, move down, focus, fullscreen enable, $bp0

$fw [$a="playlist-th"] $mto $L, focus, $bp0
$fw [$t="^/dev/video0$"] $mtw 53, fullscreen enable
$fw [$t="^/dev/video1$"] $mtw 54, fullscreen enable
$fw [$t="^Cultris II$"] $fe, move position center
$fw [$t="^File Upload$"] $rs 1024px 768px, move position center, focus

$fw [$c="^tw-com-aten-ikvm-KVMMain$"] $fe, $rs 1280px 1024px

$fw [$t="^Go to Home - iOS Accessibility Testing Guide — Mullvad Browser$"] $mtw 2, $fe, $rs 1916px 1029px, $map 1081px 380px
