
# i3 Configuration File - general window rules
$fw [$c="[aA]lacritty"] focus
$fw [$c="kdenlive"] floating enable
$fw [$c="[kK]ate"] floating enable, $rs 1020 1060
$fw [$c="[xX]fce4-terminal"] focus
$fw [$c="^adi2remote.exe$"] floating enable
$fw [$c="^ColorPicker$"] floating enable
$fw [$c="^EtG.x86_64$"] floating enable
$fw [$c="^GParted$"] floating enable
$fw [$c="explorer.exe"] $mts
$fw [$c="kalgebra"] floating enable
$fw [$a="org.pulseaudio.pavucontrol"] floating enable
$fw [$c="th19.exe"] floating enable, border none
$fw [$c="xfce-polkit"] focus
$fw [$c="Yad"] floating enable
$fw [$i="mpvcapturecard-secondary"] $mto $RR
$fw [$i="mpvcapturecard"] $mtw 54
#$fw [$i="mpvfloattopright"] $mtw 1, floating enable, $map 890px 27px, $rs 192px 108px, focus, border none
$fw [$a="mpvfloattopright"] $mtw 1, floating enable, $mr 440, move up 890, border none
$fw [$a="mpvleft"] $mto $L, $md, focus, $bp0

$fw [$a="mpvright"] $mto $R, $md, focus, fullscreen enable, $bp0

$fw [$a="playlist-th"] $mto $L, focus, $bp0
$fw [$t="^/dev/video0$"] $mtw 53, fullscreen enable
$fw [$t="^/dev/video1$"] $mtw 54, fullscreen enable
$fw [$t="^Cultris II$"] floating enable, $mpc
$fw [$t="^File Upload$"] $rs 1024px 768px, $mpc, focus

$fw [$c="^tw-com-aten-ikvm-KVMMain$"] floating enable, $rs 1280px 1024px

$fw [$t="^Go to Home - iOS Accessibility Testing Guide — Mullvad Browser$"] $mtw 2, floating enable, $rs 1916px 1029px, $map 1081px 380px

$fw [$t="^Interactive display adjustment$"] $mtw 1, floating enable, $rs 1916px 1029px, $map 1081px 380px

# Filebot
# $fw [$t="^win[0123]$"] move scratchpad
# causes weird effects to right click menu
$fw [$c="^net-filebot-Main$"] floating enable, $map 1080px 340px