# i3 Configuration File - Additional Window Rules
$fw [window_role="About"] floating enable
$fw [window_role="bubble"] floating enable
$fw [window_role="pop-up"] floating enable
$fw [window_role="Preferences"] floating enable
$fw [window_role="task_dialog"] floating enable
# $fw [window_type="dialog"] floating enable
$fw [window_type="menu"] floating enable