WHATTOSYNC=(
# Thumbnail Sources (Syncing these to RAM via ASD)
  # Build Environments (Targeting your /mnt/data1 storage)
  '/mnt/data1/cache/ccache'
  '/mnt/data1/cache/go_build'
  '/mnt/data1/cache/go_mod'
)

VOLATILE="/tmp"
USE_OVERLAYFS="yes"
ENABLE_HARDLINK_SAFETY_CHECK=1
USE_BACKUPS="yes"
BACKUP_LIMIT=5
