WHATTOSYNC=(
# Thumbnail Sources (Syncing these to RAM via ASD)
#  '/home/blu/.cache/thumbnails'
#  '/home/blu/icons'

  # Browsers & Mail
  '/home/blu/.config/BraveSoftware/Brave-Browser'
  '/home/blu/.thunderbird'

  # Graphics & System Caches
  '/home/blu/.cache/fontconfig'
  '/home/blu/.cache/mesa_shader_cache'
  '/home/blu/.cache/Moonlight Game Streaming Project'

  # Build Environments (Targeting your /mnt/data storage)
  '/mnt/data/cache/ccache'
  '/mnt/data/cache/go_build'
  '/mnt/data/cache/go_mod'

  # Python & Node (frequent small writes)
  '/home/blu/.cache/pip'
  '/home/blu/.cache/pipx'
)

VOLATILE="/tmp"
USE_OVERLAYFS="yes"
ENABLE_HARDLINK_SAFETY_CHECK=1
USE_BACKUPS="yes"
BACKUP_LIMIT=5
