# i3 Configuration File - Application Shortcuts

# Open Dolphin file manager
$bm $meta+n exec dolphin

# Capture entire screen
$bm Print exec ~/.config/i3/screenshots.sh CaptureEntireScreen

# Capture entire screen to clipboard
$bm Ctrl+Print exec ~/.config/i3/screenshots.sh CaptureEntireScreenToClipboard

# Capture selected region to clipboard
$bm Ctrl+Shift+Print exec ~/.config/i3/screenshots.sh CaptureSelectedRegionToClipboard

# Capture selected region with a unique name
$bm Shift+Print exec ~/.config/i3/screenshots.sh CaptureSelectedRegionUniqueToClipboard

# Capture active window
$bm $meta+Print exec ~/.config/i3/screenshots.sh CaptureActiveWindow 

# Capture active window to clipboard
$bm Ctrl+$meta+Print exec ~/.config/i3/screenshots.sh CaptureActiveWindowToClipboard

# Open alacritty terminal
$bm $meta+Return exec alacritty

# Reload i3 config and i3blocks
$bm $meta+Shift+c reload
$bm $meta+Shift+b exec ~/.config/i3/i3blocksreload.sh

# Restart i3
$bm $meta+Shift+r restart

# Launch Rofi app launcher
$bm Control+e exec rofi -show drun
