# i3 Configuration File - Applications Autostart

#$e mscore # musescore
$ea --no-startup-id dunst # for inotify-send etc
$e akonadictl stop
$ea --no-startup-id xautolock -time 300 -locker "xset dpms force off" -notify 30 -notifier "notify-send 'Idle for 5 minutes'" && systemctl suspend


# $e ~/apps/slippi/./Slippi.AppImage
# $e ~/cxoffice/bin/crossover
# $e ~/jd2/JDownloader2

# $e ~/scripts/mounts/mount-sshfs-user.sh
$e ~/scripts/mounts/mount-webdav.sh
$e ~/scripts/autostart/pre-wait-for-sshfsmounts-and-$e.sh
$e alacritty --class=alacritty-trackma-curses -e trackma-curses 

$e bash ~/.config/i3/unfocused-window-mute.sh
$e code # vscode
$e dex --autostart --environment i3
$e fcitx5 -d
$e lxqt-policykit-agent

$e GDK_SCALE=2 fsearch # for making fsearch font double as large
#$e idea # IntelliJ IDEA 
$e corectrl
$e keepassxc
$e mullvad connect
# $e mullvad-browser -P mullvadbrowser-real-debrid --class="mullvadbrowser-real-debrid"
$e numlockx
$e obsidian
# $e parallel-launcher
$e python3 ~/broadlink/broadlink_ui.py 
# $e ssh -L 5000:127.0.0.1:5000 -N root@tail.ws -p 764
# $e steam
# $e syncthing
# $e thunderbird
# $e virt-managerc
$e wire-desktop 
#$e ckb-next
# $e ares # other multi-platform-emulator
# $e simple64-gui
# $e bash /home/blu/scripts/autostart/delayed-i3-restart.sh
# $e autorandr --load work

# disabled ... wanna be sway compatible.
#$ea picom --config ~/.config/picom/picom.conf


# ## PERF

$e /home/blu/scripts/xrandr/setup-displays.sh
$e /home/blu/.config/i3/remove-urgent-marks.sh

$e /usr/bin/mount /sshfsmounts/2tb-1