bar {
  id bar-1
  mode dock
  output $R
  position top
  tray_output none
  separator_symbol " • "
  status_command i3blocks -c ~/.config/i3blocks/i3blocks.conf

  # Disable vertical scrolling (mousewheel changes workspace otherwise)
  bindsym button4 nop
  bindsym button5 nop

  # Disable horizontal scrolling (mousewheel changes workspace otherwise)
  bindsym button6 nop
  bindsym button7 nop

  colors {
    background #1a1a1a
    separator #4d4d4d
    statusline #ffffff

    # Aktiver Arbeitsbereich
    focused_workspace #1a1a1a #268bd2 #ffffff

    # Inaktiver Arbeitsbereich
    inactive_workspace #1a1a1a #333333 #ffffff

    # Dringender Arbeitsbereich
    urgent_workspace #ff5555 #ff5555 #ffffff

    # Arbeitsbereich inaktiv
    # active_workspace <Hintergrundfarbe> <Borderrahmenfarbe> <Textfarbe>
    active_workspace #1a1a1a #6c71c4 #ffffff
  }
}


bar {
  id bar-2
  #workspace_buttons no
  output $L
  position top
  tray_output none
  separator_symbol " • "
  status_command i3blocks -c ~/.config/i3blocks/i3blocks-lean.conf

  # Disable vertical scrolling (mousewheel changes workspace otherwise)
  bindsym button4 nop
  bindsym button5 nop

  # Disable horizontal scrolling (mousewheel changes workspace otherwise)
  bindsym button6 nop
  bindsym button7 nop

  colors {
    background #1a1a1a
    separator #4d4d4d
    statusline #ffffff

    # Aktiver Arbeitsbereich
    focused_workspace #1a1a1a #268bd2 #ffffff

    # Inaktiver Arbeitsbereich
    inactive_workspace #1a1a1a #333333 #ffffff

    # Dringender Arbeitsbereich
    urgent_workspace #ff5555 #ff5555 #ffffff

    # Arbeitsbereich inaktiv
    # active_workspace <Hintergrundfarbe> <Borderrahmenfarbe> <Textfarbe>
    active_workspace #1a1a1a #6c71c4 #ffffff
  }
}
