# 01-mediakeys.conf
$bm {
    # media control - general
    XF86AudioLowerVolume $ensi wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    XF86AudioMicMute $ensi wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    XF86AudioMute $ensi wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    XF86AudioRaiseVolume $ensi wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+
    # media control - mpv
    XF86AudioNext $ensi ~/.config/sway/scripts/mediacontrol.bash next
    XF86AudioPlay $ensi ~/.config/sway/scripts/mediacontrol.bash pause
    XF86AudioPrev $ensi ~/.config/sway/scripts/mediacontrol.bash prev
    XF86AudioStop $ensi ~/.config/sway/scripts/mediacontrol.bash stop

    # Toggles RME ADI-2 DAC FS from PH to LINE and so on
    $meta+XF86AudioMute $ensi amidi -l | awk '/ADI-2 DAC/ {print $2}' | xargs -I {} amidi -p {} -S "F0 00 20 0D 71 02 67 70 01 F7"
    Control+XF86AudioMute $ensi amidi -l | awk '/ADI-2 DAC/ {print $2}' | xargs -I {} amidi -p {} -S "F0 00 20 0D 71 02 67 70 01 F7"
}