# 04-app-autostart.conf
# exec /usr/bin/kdenlive
# exec /usr/bin/mdbook serve /mnt/n/iOS-Accessibility-Guide -p 3000 -n 0.0.0.0
# exec /usr/bin/nvtop
# exec /usr/bin/steam -no-browser
# exec antimicrox --hidden # replaced with input-remapoper
exec /usr/bin/code-server --auth none --disable-telemetry
exec /usr/lib/xdg-desktop-portal -r
exec ~/.config/sway/scripts/alacritty-micro-stickies/startup.bash
exec ~/apps/slippi/./Slippi.AppImage --no-sandbox
exec ~/scripts/autostart/script-startup.bash
exec ~/scripts/autostart/start_keyboard-watcher.bash
exec ~/scripts/cronjobs/watch-borgbackup-log.bash
exec akonadictl stop
exec code # vscode
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec dex --autostart --environment sway
exec discord
exec env RUST_BACKTRACE=1 RUST_LOG=swayr=debug swayrd >> /tmp/swayrd.log 2>&1
exec fcitx5 -d
exec gammastep
exec keepassxc
exec mako
exec mullvad connect
exec thunderbird
exec_always killall at-spi2-registryd; killall at-spi-bus-launcher


#pipewire

exec pw-metadata -n settings 0 clock.force-quantum 256
exec qpwgraph -m -a /home/blu/.config/sway/qpwgraph/mapping.qpwgraph
exec qpwgraph -m -a /home/blu/.config/sway/qpwgraph/mapping.qpwgraph