# sway Configuration File - general window rules
$fw {
     [window_role="About"] floating enable
     [window_role="bubble"] floating enable
     [window_role="pop-up"] floating enable
     [window_role="Preferences"] floating enable
     [window_role="task_dialog"] floating enable
# [window_type="dialog"] floating enable
     [window_type="menu"] floating enable
}

$fw { 
    # $fw [$c="Pianoteq"] floating enable, move to scratchpad
    [$a="^alacritty-micro-cursor-*$"] floating enable, move to position cursor
    [$a="^alacritty-micro-startup-intake$"] $mtw $ws01-R, splitv, layout toggle split, border pixel none
    [$a="^alacritty-micro-startup-wanikani-cheat$"] $mtw $ws08-M, splith, resize set width 75 ppt
    [$a="^alacritty-micro-startup-wellbeing$"] $mtw $ws01-R, splith, layout toggle split, border pixel none
    [$a="^mpv_mon_kb$"] move to output $MON_KBq
    [$a="^mpvfloattopright$"] $mtw 2, $fe, $map 1965px 350px, border none, sticky enable, opacity 1
    [$a="^mpvleft$"] $mto $L, $md, $f, $bp0
    [$a="^mpvright$"] $mto $R, $fs
    [$a="^mpvmiddle$"] $mto $M, $fs
    [$a="^Mullvad VPN$"] move to scratchpad
    [$a="^org.kde.okular$"] $fe
    [$a="^org.pulseaudio.pavucontrol$"] $fe, $rs 1024px 768px
    [$a="^playlist-th$"] $mto $L, $f, $bp0
    [$a="^SVPManager$"] $fe, $rs 1916px 1029px, $map 1081px 380px
    [$a="^xfce-polkit$"] $fe
    [$a="alacritty-time"] $mtw 1, $fe, $rs 247px 247px, $map 832px 1671px
    [$a="Alacritty"] border pixel 1
    [$a="code-oss"] $mto $M, focus
    [$a="com.github.wwmm.easyeffects"] move to scratchpad, scale 0.7
    [$c="[aA]lacritty"] $f
    [$c="[cC]ode"] $mto $M, focus
    [$c="[kK]ate"] $fe, $rs 1020 1060
    [$c="[xX]fce4-terminal"] $f
    [$c="^adi2remote.exe$"] $fe
    [$c="^code-oss$"] $mto $M, focus
    [$c="^ColorPicker$"] $fe
    [$c="^EtG.x86_64$"] $fe
    [$c="^explorer.exe$"] $mts
    [$c="^GParted$"] $fe
    [$c="^kalgebra$"] $fe
    [$c="^net-filebot-Main$"] $fe, $map 1080px 340px
    [$c="^th19.exe$"] $fe, border none
    [$c="^tw-com-aten-ikvm-KVMMain$"] $fe, $rs 1280px 1024px
    [$c="^Yad$"] $fe
    [$i="^mpvcapturecard-secondary$"] $mto $RR
    [$i="^mpvcapturecard$"] $mtw 54
    [$i="^vscodium$"] $mto $M, focus
    [$t="^/dev/video0$"] $mtw 53, $fs
    [$t="^/dev/video1$"] $mtw 54, $fs
    [$t="^C2 Settings$"] $fe
    [$t="^Chat with Amazon Customer Service ー Mozilla Firefox$"] $fe, $rs 400px 400px
    [$t="^Cultris II$"] $fe, $mpc, max_render_time 1, center
    [$t="^File Upload$"] $rs 1024px 768px, $mpc, $f
    [$t="^Go to Home - iOS Accessibility Testing Guide — Mullvad Browser$"] $mtw 2, $fe, $rs 1916px 1029px, $map 1081px 380px
    [$t="^Interactive display adjustment$"] $mtw 1, $fe, $rs 1916px 1029px, $map 1081px 380px

    [shell="^xwayland$"] title_format '%title 𝓧'
    [shell="^wayland$"] title_format '%title ᭙'

    # TODO
      
    [$c="^chrome-taiko-cjdgrevival$"] $mtw 7
    
    [$a="^taiko_screen_screensaver$"] move to workspace 5, fullscreen enable
}

