# 06-general-win-rules.conf
$fw {
     [window_role="About"] floating enable
     [window_role="bubble"] floating enable
     [window_role="pop-up"] floating enable
     [window_role="Preferences"] floating enable
     [window_role="task_dialog"] floating enable
# [window_type="dialog"] floating enable
     [window_type="menu"] floating enable
}

$fw { 
    # $fw [$c="Pianoteq"] floating enable, move to scratchpad
    [$a="^alacritty-micro-cursor-*$"] floating enable, move to position cursor
    [$a="^alacritty-micro-startup-intake$"] $mtw $ws01-R, splitv, layout toggle split, border pixel none
    [$a="^alacritty-micro-startup-wanikani-cheat$"] $mtw $ws08-M, splith, resize set width 75 ppt
    [$a="^alacritty-micro-startup-wellbeing$"] $mtw $ws01-R, splith, layout toggle split, border pixel none
    [$a="^cachy-.*$" $t="About Cachy Browser"] floating enable
    [$a="^io.github.dimtpap.coppwr$"] floating enable
    [$a="^mpv_mon_kb$"] move to output $MON_KB
    [$a="^mpvmiddle$"] $mto $M, fullscreen enable
    [$a="^mpvright$"] $mto $R, fullscreen enable
    [$a="^Mullvad VPN$"] move to scratchpad
    [$a="^org.kde.okular$"] floating enable
    [$a="^org.pulseaudio.pavucontrol$"] floating enable, resize set 1024px 768px
    [$a="^SVPManager$"] floating enable, resize set 1916px 1029px, $map 1081px 380px
    [$a="^xfce-polkit$"] floating enable
    [$a="Alacritty"] border pixel 1
    [$a="code-oss"] $mto $M, focus
    [$a="com.github.wwmm.easyeffects"] move to scratchpad, scale 0.7
    [$c="[cC]ode"] $mto $M, focus
    [$c="[kK]ate"] floating enable, resize set 1020 1060
    [$c="^adi2remote.exe$"] floating enable
    [$c="^code-oss$"] $mto $M, focus
    [$c="^ColorPicker$"] floating enable
    [$c="^EtG.x86_64$"] floating enable
    [$c="^explorer.exe$"] $mts
    [$c="^GParted$"] floating enable
    [$c="^kalgebra$"] floating enable
    [$c="^net-filebot-Main$"] floating enable, $map 1080px 340px
    [$c="^th19.exe$"] floating enable, border none
    [$c="^tw-com-aten-ikvm-KVMMain$"] floating enable, resize set 1280px 1024px
    [$c="^Yad$"] floating enable
    [$i="^mpvcapturecard-secondary$"] $mto $RR
    [$i="^mpvcapturecard$"] $mtw 54
    [$i="^vscodium$"] $mto $M, focus
    [$t="^/dev/video0$"] $mtw 53, fullscreen enable
    [$t="^/dev/video1$"] $mtw 54, fullscreen enable
    [$t="^C2 Settings$"] floating enable  
    [$t="^Cultris II$"] floating enable, $mpc, max_render_time 1, center
    [$t="^File Upload$"] resize set 1024px 768px, $mpc, floating enable
    [$t="^GameCube Controller Configuration Port (1|2|3|4)$"] floating enable, resize set 1024 1024
    [$t="^Interactive display adjustment$"] $mtw 1, floating enable, resize set 1916px 1029px, $map 1081px 380px
    [$t="^Save Image$"] center
    [shell="^wayland$"] title_format '%title ᭙'
    [shell="^xwayland$"] title_format '%title 𝓧'

   [$a="^mpvfloat[0-9]+$"] move to workspace 18, floating enable, border none
   

    # TODO
      
    [$a="^chrome-taiko-cjdgrevival$"] move to output $TAIKO, focus
    
    
}
