
$fw {
    # Floating Rules
    [window_role="About|bubble|pop-up|Preferences|task_dialog|menu"] floating enable
    [$a="^alacritty-micro-cursor-*$"] floating enable, move to position cursor
    [$a="^nm-connection-editor$"] floating enable
    [$a="^cachy-.*$" $t="About Cachy Browser"] floating enable
    [$a="^io.github.dimtpap.coppwr$"] floating enable
    [$a="^org.kde.okular$"] floating enable
    [$a="^org.pulseaudio.pavucontrol$"] floating enable, resize set 1024px 768px
    [$a="^SVPManager$"] floating enable, resize set 1916px 1029px, $map 1081px 380px
    [$a="^xfce-polkit$"] floating enable, move to workspace 3, sticky enable, focus
    [$c="^adi2remote.exe$"] floating enable
    [$c="^ColorPicker$"] floating enable
    [$c="^EtG.x86_64$"] floating enable
    [$c="^GParted$"] floating enable
    [$c="^kalgebra$"] floating enable
    [$c="^steam$"] floating enable
    [$c="^th19.exe$"] floating enable, border none
    [$a="^yad$"] floating enable
    [$sh="^xwayland$" title="^Steam$"] floating enable
    [instance="^steamwebhelper$"] floating enable
    [$sh="^xwayland$" title="^Cultris II$"] floating enable, center
    
    # Scratchpad Rules
    [$a="^Mullvad VPN$"] move to scratchpad
    [$c="^explorer.exe$"] $mtscratch
    [$a="^com.github.wwmm.easyeffects$"] move to scratchpad, scale 0.7

    # Output and Focus Rules
    [$a="^mpv_mon_kb$"] move to output $MON_KB
    [$a="^mpvmiddle$"] $mto $M, fullscreen enable
    [$a="^mpvright$"] $mto $R, fullscreen enable
    [$i="^vscodium$"] $mto $M, focus

    # title_formats
    [shell="^xdg_shell$"] title_format '%title ᭙'
    [shell="^xwayland$"] title_format '%title 𝓧'

    [shell="^xwayland" title="^OpenTaiko Ver.*^" ] move to output $TAIKO
}
