# i3 Configuration File - Additional Window Rules
$fw {
     [window_role="About"] floating enable
     [window_role="bubble"] floating enable
     [window_role="pop-up"] floating enable
     [window_role="Preferences"] floating enable
     [window_role="task_dialog"] floating enable
# [window_type="dialog"] floating enable
     [window_type="menu"] floating enable
}
