# Common Configuration
set $separator_symbol " • "
set $background_color #002b36
set $separator_color #839496
set $active_workspace_color #fdf6e3 #6c71c4 #fdf6e3
set $focused_workspace_color #fdf6e3 #268bd2 #fdf6e3
set $inactive_workspace_color #002b36 #002b36 #268db2
set $urgent_workspace_color #d33682 #d33682 #fdf6e3
set $statusline_color #eff0f1

# Bar-specific status commands
set $status_command_lean i3blocks -c ~/.config/i3blocks/i3blocks-lean.conf
set $status_command_default i3blocks -c ~/.config/i3blocks/i3blocks.conf
set $status_command_mon i3blocks -c ~/.config/i3blocks/i3blocks-mon.conf


bar {
  id bar-1
  output { 
    $LL   
    $L    
    $R    
    $RR   
    $TAIKO
  }
  position top
  tray_output none
  separator_symbol $separator_symbol
  status_command $status_command_lean

  colors {
    active_workspace $active_workspace_color
    background $background_color
    focused_workspace $focused_workspace_color
    inactive_workspace $inactive_workspace_color
    separator $separator_color
    statusline $statusline_color
    urgent_workspace $urgent_workspace_color
  }
}

bar {
  id bar-3
  mode dock
  output $M
  position top
  tray_output none
  separator_symbol $separator_symbol
  status_command $status_command_default

  colors {
    active_workspace $active_workspace_color
    background $background_color
    focused_workspace $focused_workspace_color
    inactive_workspace $inactive_workspace_color
    separator $separator_color
    statusline $statusline_color
    urgent_workspace $urgent_workspace_color
  }
}


bar {
  id bar-5
  output $MON_KB
  position top
  tray_output none
  separator_symbol $separator_symbol
  status_command $status_command_mon

  colors {
    active_workspace $active_workspace_color
    background $background_color
    focused_workspace $focused_workspace_color
    inactive_workspace $inactive_workspace_color
    separator $separator_color
    statusline $statusline_color
    urgent_workspace $urgent_workspace_color
  }
}