# 08-input-automation-fkeys.conf

$bm {
   $meta+F10 $ensi /home/blu/Downloads/c2/automate-c2-input-sequence_two
   $meta+F12 $ensi "[ -z $(pgrep -x dotoold) ] && dotoold & sleep 1 && echo type $(wl-paste) | dotoolc"
} 