# 08-input-automation-fkeys.conf

# $bc {
#     196 $ensi '/home/blu/.config/sway/scripts/tripleclick.bash' &&  < "/home/blu/.config/sway/bitv-copy-click-translate.txt" dotoolc
# } 
# $bm {
#     $meta+F12 $ensi echo type $(wl-paste) | dotool
#     $meta+F10 $ensi < "/home/blu/.config/input-automation-dotool/sway/bitv-template.txt" dotool
# } 

$bm {
   $meta+F10 $ensi /home/blu/Downloads/c2/automate-c2-input-sequence_two
   $meta+F12 $ensi "[ -z $(pgrep -x dotoold) ] && dotoold & sleep 1 && echo type $(wl-paste) | dotoolc"
} 