# 09-microstickies.conf

### microstickies

set $microstickies "/home/blu/.config/sway/scripts/alacritty-micro-stickies/micro-stickies.bash"
$bm $meta+c $ensi $microstickies blue --cursor
# mode "ncolor" {

# bindsym     1       $ensi     $microstickies        blue
# bindsym     2       $ensi     $microstickies        orange
# bindsym     3       $ensi     $microstickies        purple
# bindsym     4       $ensi     $microstickies        green
# bindsym     5       $ensi     $microstickies        red
# bindsym     9       $ensi     $microstickies        transparent

#     # Return to default mode
# bindsym Return mode "default"
# bindsym Escape mode "default"
# }
# bindsym F11 mode "ncolor"

##################