# 11-gamepad-shortcuts.conf
# Gamepad Shortcuts (F23, F24)
$bc {
    201 $ensi swaymsg '[$c="^dolphin-emu$" window_role="renderer" instance="AppRun.wrapped"] focus'
    #202 $ensi swaymsg workspace 1, workspace 2, workspace 3, workspace 4
    202 $ensi wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}