# 11-gamepad-shortcuts.conf
# Gamepad Shortcuts (F23, F24)
 $bc {
      202 $ensi swaymsg '[title="Dolphin"] focus'
#     #202 $ensi swaymsg workspace 1, workspace 2, workspace 3, workspace 4
    
 }

#bindsym F23 $ensi swaymsg '[title="Dolphin"] focus'