mode "mark-for-move" {
    bindsym Ctrl+Home exec "swaymsg -t get_tree | jq '.. | objects | select(.focused == true) | .id' > /tmp/sway-window-id"; mode "move-to-workspace"
    bindsym Escape mode "default"
}
