#!/bin/bash

# The two outputs to toggle between
OUTPUT_A="DP-7"
OUTPUT_B="DP-3"

# Get the current output of the marked window
CURRENT_OUTPUT=$(swaymsg -t get_tree | jq -r '.. | objects | select(.marks? and (.marks | index("tempmark"))) | .output')

if [ "$CURRENT_OUTPUT" = "$OUTPUT_A" ]; then
    swaymsg '[con_mark="tempmark"] move to output '"$OUTPUT_B"
else
    swaymsg '[con_mark="tempmark"] move to output '"$OUTPUT_A"
fi
