# af=lavfi=[loudnorm=I=-18:TP=-3:LRA=4]
# replaygain=track
directory-filter-types=audio,video
osd-level=2
osd-scale=4
profile-desc="Normalize audio volume"
save-position-on-quit

replaygain=album
replaygain-preamp=0
replaygain-clip=no 
