# 10-output-disable-enable.conf
# bindsym $meta+m 'output * toggle'
$bm { 
  $meta+m $ensi swaymsg -t get_outputs | jq -r '.[].name' | xargs -I{} swaymsg output {} disable    
  $meta+period swaymsg -t get_outputs | jq -r '.[].name' | xargs -I{} swaymsg output {} enable  
} 
